### ISSUE TITLE
Does not seem to work with Buffers?

### ISSUE THREAD

**Issue by OrKoN** [blockai/persistent-memoize#1]
Hey,

I am trying to use persistent-memoize with fs-blob-store. My memoized function returns a Buffer. The first run (nothing is persisted) is successful and I get the correct Buffer object back. When I run it again I get a different buffer which contains wrong data. Looks like persistent-memoize appends something to the data before persisting it... Is it supposed to work like this? My understanding was that memoized functions should always return the same data.

Thanks in advance
Alex

**Comment by OrKoN** [comment]
For example,

```
not cached: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 04 00 00 00 03 00 08 06 00 00 00 ba ba 15 0d 00 00 00 09 70 48 59 73 00 00 0b 13 00 00 0b 13 01 ... >
cached: <Buffer ef bf bd 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 04 00 00 00 03 00 08 06 00 00 00 ef bf bd ef bf bd 15 0d 00 00 00 09 70 48 59 73 00 00 0b ... >
```

The code is like this:

```
var renderUrl = (url) => {
  return new Promise((resolve, reject) => {
    request({
      url: 'http://localhost:8080/',
      json: {
        url,
        siteType: 'url',
      },
      method: 'POST',
      encoding: null,
    }, (err, res, body) => {
      if (err) {
        return reject(err);
      }
      resolve(body);
    })
  });
}

const renderUrlMemo = memoize(renderUrl, 'renderUrlMemo');

router.post('/', function(req, res, next) {
  var url = req.body.url;
  renderUrlMemo(url).then(r => {
    console.log(r);
    res.set('Content-Type', 'image/png');
    res.end(r, 'binary');
  }).catch(err => {
    res.end();
  });
});
```

**Comment by olalonde** [comment]
Thanks for reporting this, I will investigate. I've mostly tested this module with stream returning functions. The results are stored in files with the first line containing some metadata encoded as JSON (like variable type and creation date) but it should not be visible to users.

**Comment by olalonde** [comment]
I tried adding this test which passes:

```javascript
test('issue #1', (t) => {
  const getBody = (url) => new Promise((resolve, reject) => {
    request({
      url,
      encoding: null,
    }, (err, res, body) => {
      if (err) {
        return reject(err)
      }
      resolve(body)
    })
  })
  const memoGetBody = memoize(getBody, 'getHNStory')

  const url = 'https://raw.githubusercontent.com/blockai/persistent-memoize/master/test/poem.txt'
  let firstBody
  let secondBody
  return memoGetBody(url)
    .then((body) => {
      firstBody = body
      console.log(body)
    })
    .then(() => memoGetBody(url))
    .then((body) => {
      secondBody = body
      console.log(body)
    })
    .then(() => {
      t.ok(Buffer.isBuffer(firstBody))
      t.ok(Buffer.isBuffer(secondBody))
      t.deepEqual(firstBody, secondBody)
    })
})
```

Weird... could you try modifying the test so that it reproduces the bug you are experiencing?

**Comment by olalonde** [comment]
The test is here: https://github.com/blockai/persistent-memoize/blob/master/test/index.js#L150

You can run tests by cloning the repo and `npm install; npm test`

**Comment by olalonde** [comment]
Is it possible that you bumped your package version? persistent-memoize uses your package version by default to decide whether the cache is stale. You can disable this by manually specifying a version when you initialise memoize:

```javascript
const memoize = initMemoize(blobStore, { version: 'latest' })
```

for example.

**Comment by OrKoN** [comment]
@olalonde try replacing the URL with `https://raw.githubusercontent.com/maxogden/abstract-blob-store/master/badge.png` This breaks the test

**Comment by olalonde** [comment]
OrKoN ok thanks, will try.

**Comment by olalonde** [comment]
Ok, I think I fixed this. The "parseHeader" function was broken if the body contained "invalid" utf-8. Published as `0.0.3`.

**Comment by olalonde** [comment]
Thanks for reporting this 👍

**Comment by OrKoN** [comment]
Thanks! Works great now!
